### ISSUE TITLE
Feature Request: ToC markers to be compatible with toc-me GitHub App

### ISSUE THREAD

**Issue by jasonkarns** [technote-space/toc-generator#232]
I (and I believe many others) have long used a GitHub probot for automatic ToC generation:
https://github.com/pholleran/toc-me

For ease of compatibility, would it be acceptable to use compatible toc marker comments?

`<!-- toc -->` and `<!-- tocstop -->` ?

**Comment by technote-space** [comment]
OK, I will add toc marker comments option and set the value for toc-me as default

**Comment by technote-space** [comment]
@jasonkarns 
I added the options.

- OPENING_COMMENT = `<!-- toc `
- CLOSING_COMMENT = `<!-- tocstop `

Please use v2.3.0 or v2.3 or v2.
